### PR TITLE
HWPV-95: Remove post office payout code

### PR DESCRIPTION
**Pull request by psoleckimoj**

### CODE REVIEW

**Review by tpmcgowan — APPROVED** [review]
LGTM!

**Comment by simonnebMOJ** [comment]
This needs to be implemented on evening of 7 January 2024 @psoleckimoj

**Comment by psoleckimoj** [comment]
@simonnebMOJ we need to get this into dev at the beginning of the week as well as preprod and ensure it works. Would be happy for Simon etc to get someone to check it if they can.

**Review by tpmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
